ckeditor/ckeditor5-integrations-common

src/cdn/ck/createCKCdnBaseBundlePack.ts, src/cdn/ck/createCKCdnPremiumBundlePack.ts, src/cdn/ck/globals.d.ts, src/cdn/ckbox/createCKBoxCdnBundlePack.ts, src/cdn/ckbox/globals.d.ts, src/index.ts
Fix: Add missing `declare global` CKEditor variables to final `index.d.ts` bundle. 
---
It was causing missing type information in hooks / composable results.
=> Adjust wrong global imports

CHANGELOG.md
Internal: Changelog for v0.1.1.
=> Release - add missing CKEditor window variables to final `index.d.ts` bundle.

src/utils/uid.ts, tests/utils/uid.test.ts
Internal: Remove `Math.random()` from `uid` implementation. See https://github.com/cksource/ckeditor5-internal/issues/3742.
---
Follow-up of: https://github.com/ckeditor/ckeditor5/pull/16945
=> Remove Math.random from uid

src/cdn/ck/globals.d.ts, src/cdn/ckbox/globals.d.ts
Fix: No longer raise `export modifier cannot be applied to ambient modules` error on older TS versions.
---
While newer versions of TS (`5.5.4`) don't complain about `export declare` (which is crucial for some augmentations in local functions), the older TS versions (`5.1.0`) complain about this:
`skipLibCheck` must be set to `false` in importing project.
=> Fix `export declare` compiler fails on older TS versions

.circleci/config.yml, package.json, src/cdn/ck/createCKCdnBaseBundlePack.ts, src/cdn/ck/createCKCdnPremiumBundlePack.ts, src/cdn/ckbox/createCKBoxCdnBundlePack.ts, src/cdn/combineCKCdnBundlesPacks.ts, src/cdn/loadCKCdnResourcesPack.ts, src/cdn/loadCKEditorCloud.ts, src/cdn/plugins/combineCdnPluginsPacks.ts, src/index.ts, src/utils/filterBlankObjectValues.ts, src/utils/filterObjectValues.ts, src/utils/injectScript.ts, src/utils/injectStylesheet.ts, src/utils/mapObjectValues.ts, src/utils/preloadResource.ts, tests/_utils/index.ts, tests/_utils/queryHeadElement.ts, tests/cdn/ck/createCKCdnBaseBundlePack.test.ts, tests/cdn/ck/createCKCdnPremiumBundlePack.test.ts, tests/cdn/ckbox/createCKBoxBundlePack.test.ts, tests/cdn/combineCKCdnBundlesPacks.test.ts, tests/cdn/loadCKCdnResourcesPack.test.ts, tests/cdn/loadCKEditorCloud.test.ts, tests/cdn/plugins/combineCKPluginsPacks.test.ts, tests/utils/filterBlankObjectValues.test.ts, tests/utils/filterObjectValues.test.ts, tests/utils/mapObjectValues.test.ts, tests/utils/preloadResource.test.ts, tsconfig.test.json
The API interface of the loadCKEditorCloud method has been simplified, and the ability to specify the CKBox theme has been added.
---
```tsx
const { CKEditor, loadedPlugins } = await loadCKEditorCloud( {
version: '43.0.0',
plugins: {
// New one, example: local UMD plugins
Plugin1: async () => import( './your-local-import.umd.js' ),
// New one, example: local external imports
// Additional bundler configuration must be used, like this one: 
// https://github.com/crcong/vite-plugin-externals
Plugin11: async () => import( './your-local-import' ) as unknown as Promise<Your_Type>,
// New one, example: CDN 3rd party
Plugin2: [
'https://cdn.example.com/plugin2.js',
'https://cdn.example.com/plugin2.css'
],
// Old one, verbose for more advanced plugins. It's still available.
Plugin3: {
scripts: [ …
```
=> Simplify end user API

package.json, src/cdn/ck/createCKCdnBaseBundlePack.ts, src/cdn/ck/createCKCdnPremiumBundlePack.ts, src/cdn/ckbox/createCKBoxCdnBundlePack.ts, src/cdn/combineCKCdnBundlesPacks.ts, src/cdn/loadCKCdnResourcesPack.ts, src/cdn/loadCKEditorCloud.ts, src/cdn/plugins/combineCdnPluginsPacks.ts, tests/cdn/ck/createCKCdnBaseBundlePack.test.ts, tests/cdn/ck/createCKCdnPremiumBundlePack.test.ts, tests/cdn/ckbox/createCKBoxBundlePack.test.ts, tests/cdn/combineCKCdnBundlesPacks.test.ts, tests/cdn/loadCKCdnResourcesPack.test.ts, tests/cdn/loadCKEditorCloud.test.ts, tests/cdn/plugins/combineCKPluginsPacks.test.ts, tsconfig.test.json
Internal: Rename `confirmPluginReady` to `checkPluginLoaded`.
---
Based on this comment:
https://github.com/ckeditor/ckeditor5-integrations-common/pull/15#issuecomment-2311137475
=> Rename `confirmPluginReady` to `checkPluginLoaded`

src/cdn/loadCKCdnResourcesPack.ts, src/utils/injectStylesheet.ts, tests/cdn/loadCKCdnResourcesPack.test.ts, tests/utils/injectStylesheet.test.ts
Feature: CSS scripts are now injected at the beginning of the document head, allowing for easier overriding of editor styles.
=> Inject stylesheets at the start of the head instead of the end. 

src/utils/injectStylesheet.ts, src/utils/preloadResource.ts, tests/cdn/loadCKCdnResourcesPack.test.ts, tests/cdn/loadCKEditorCloud.test.ts, tests/cdn/plugins/combineCKPluginsPacks.test.ts, tests/utils/filterBlankObjectValues.test.ts, tests/utils/filterObjectValues.test.ts, tests/utils/injectStylesheet.test.ts
Fix: Ensure that preload link tags are injected before stylesheet link tags.
---
This PR ensures that injected stylesheet tags are placed _after_ preload tags, just to make sure the browser properly queues preloading.
=> Ensure that preload link tags are injected before stylesheet link tags

CHANGELOG.md, README.md
Release `1.0.0` version with minor fixes in stylesheet injector order. 
---
Internal: Changelog for v1.0.0.
=> Changelog for v1.0.0

src/cdn/loadCKEditorCloud.ts, src/types/ConditionalBlank.ts, tests/cdn/loadCKEditorCloud.test.ts
Feature: `CKEditorCloudResult` now returns more narrowly typed attributes for `CKBox` and `CKEditorPremiumFeatures`, taking into account `CKEditorCloudConfig`. Closes https://github.com/ckeditor/ckeditor5-integrations-common/issues/24
```tsx
const { CKEditorPremiumFeatures } = await loadCKEditorCloud( {
version: '43.0.0',
premium: true,
ckbox: {
version: '2.5.1'
}
} );
```
**Before:**
`CKEditorPremiumFeatures` is nullable type.
**After**:
`CKEditorPremiumFeatures` is not nullable type because `premium: true` is passed.
=> Narrow typing of `loadCKEditorCloud` result

src/cdn/ck/createCKCdnBaseBundlePack.ts, src/cdn/ck/createCKCdnPremiumBundlePack.ts, src/cdn/ckbox/createCKBoxCdnBundlePack.ts, src/cdn/combineCKCdnBundlesPacks.ts, src/cdn/loadCKEditorCloud.ts, src/cdn/plugins/combineCdnPluginsPacks.ts, src/cdn/utils/combineCKCdnBundlesPacks.ts, src/cdn/utils/loadCKCdnResourcesPack.ts, src/index.ts, src/utils/without.ts, tests/cdn/ck/createCKCdnBaseBundlePack.test.ts, tests/cdn/ck/createCKCdnPremiumBundlePack.test.ts, tests/cdn/utils/combineCKCdnBundlesPacks.test.ts, tests/cdn/utils/loadCKCdnResourcesPack.test.ts, tests/utils/without.test.ts
Fix: Rename the `languages` configuration property to `translations` in `loadCKEditorCloud`.
Feature: The `en` language is no longer loaded when passed in `translations` as it is prebundled.
MINOR BREAKING CHANGE: The `languages` configuration property has been renamed to `translations` in `loadCKEditorCloud`.
=> Rename `languages` to `translations` config entry.

src/cdn/ck/createCKCdnBaseBundlePack.ts, src/cdn/ck/createCKCdnPremiumBundlePack.ts, src/cdn/loadCKEditorCloud.ts, src/cdn/utils/loadCKCdnResourcesPack.ts, src/utils/injectScript.ts, src/utils/injectStylesheet.ts, src/utils/preloadResource.ts, tests/_utils/queryInjectedElements.ts, tests/cdn/loadCKEditorCloud.test.ts, tests/utils/injectScript.test.ts, tests/utils/injectStylesheet.test.ts, tests/utils/preloadResource.test.ts
Feature: Add the `crossorigin=anonymous` attribute to all CDN resource tags to prevent CORS issues. Closes https://github.com/ckeditor/ckeditor5-integrations-common/issues/30.
Feature: Add the `injectedHtmlElementsAttributes` attribute to the `loadCKEditorCloud` configuration, allowing the addition of `nonce` and other custom attributes to injected elements.
=> Add `crossorigin=anonymous` attribute to all inserted CDN resources tags

CHANGELOG.md
Release of `2.0.0` version with minor improvements in typings and configuration format.
---
Internal: Changelog for v2.0.0.
=> Release `2.0.0`

src/cdn/ck/createCKCdnBaseBundlePack.ts, src/cdn/ck/createCKCdnPremiumBundlePack.ts, src/cdn/ck/createCKCdnUrl.ts, src/cdn/ckbox/createCKBoxCdnBundlePack.ts, src/cdn/ckbox/createCKBoxCdnUrl.ts, src/cdn/plugins/combineCdnPluginsPacks.ts, src/cdn/utils/combineCKCdnBundlesPacks.ts, src/cdn/utils/loadCKCdnResourcesPack.ts, src/docs/createCKDocsUrl.ts, src/installation-info/getCKBaseBundleInstallationInfo.ts, src/installation-info/getCKBoxInstallationInfo.ts, src/installation-info/types.ts, src/utils/isSemanticVersion.ts, tests/cdn/ck/createCKCdnBaseBundlePack.test.ts, tests/cdn/ck/createCKCdnPremiumBundlePack.test.ts, tests/cdn/ckbox/createCKBoxBundlePack.test.ts, tests/cdn/ckbox/createCKBoxCdnBundlePack.test.ts, tests/cdn/loadCKEditorCloud.test.ts, tests/cdn/plugins/combineCKPluginsPacks.test.ts, tests/cdn/utils/loadCKCdnResourcesPack.test.ts, tests/docs/createCKDocsUrl.test.ts, tests/installation-info/getCKBaseBundleInstallationInfo.test.ts, tests/installation-info/getCKBoxInstallationInfo.test.ts, tests/utils/injectScript.test.ts, tests/utils/isSemanticVersion.test.ts
Feature: Improved error readability in `loadCKEditorCloud`. It should now detect existing editor instances and provide migration info from NPM to CDN.
=> Improve CDN installation errors

package.json, src/cdn/ck/createCKCdnBaseBundlePack.ts, src/cdn/ck/createCKCdnPremiumBundlePack.ts, src/cdn/ck/createCKCdnUrl.ts, src/cdn/ck/globals.d.ts, src/cdn/ckbox/createCKBoxCdnBundlePack.ts, src/cdn/ckbox/createCKBoxCdnUrl.ts, src/cdn/plugins/combineCdnPluginsPacks.ts, src/cdn/utils/combineCKCdnBundlesPacks.ts, src/cdn/utils/loadCKCdnResourcesPack.ts, src/docs/createCKDocsUrl.ts, src/installation-info/getCKBaseBundleInstallationInfo.ts, src/installation-info/getCKBoxInstallationInfo.ts, src/installation-info/types.ts, tests/tsconfig.json, tsconfig.json, vite.test-utils.config.ts
Fix: Polyfill `ckeditor5` and `ckeditor5-premium-features` typings if these packages are not installed.
Fix: No longer use aliases in `src/` files due to incorrect `.d.ts` output. 
---
It fixes this issue:
https://github.com/ckeditor/ckeditor5-angular/issues/447
Some package managers do not install `ckeditor5-premium-features` peer dependency, which cause `tsc` to fail if `skipLibCheck: false` is set in `tsconfig.json`
=> Polyfill `ckeditor5` and `ckeditor5-premium-features` typings if these packages are not installed.

src/cdn/ck/createCKCdnBaseBundlePack.ts, src/cdn/ck/createCKCdnPremiumBundlePack.ts, src/cdn/ckbox/createCKBoxCdnBundlePack.ts, src/cdn/loadCKEditorCloud.ts, tests/cdn/ck/createCKCdnBaseBundlePack.test.ts, tests/cdn/ck/createCKCdnPremiumBundlePack.test.ts, tests/cdn/ckbox/createCKBoxCdnBundlePack.test.ts, tests/cdn/loadCKEditorCloud.test.ts
Feature: Add `createCustomCdnUrl` configuration option that allows to override default CKEditor5 Cloud CDN urls.
=> Add option to override CDN link configuration

src/cdn/ckbox/createCKBoxCdnBundlePack.ts, tests/cdn/ckbox/createCKBoxCdnBundlePack.test.ts
Feature: Add support for CKBox translations in CDN injector.
---
We forgot to add support for internationalization in `CKBox` bundle CDN loader.  It's specified in docs: https://ckeditor.com/docs/ckbox/latest/guides/configuration/localization.html. I added an optional `translations` property to allow users to specify languages to load.
=> Add support for CKBox translations in CDN injector.

CHANGELOG.md
1. Added the `createCustomCdnUrl` configuration option to override default CKEditor 5 Cloud CDN URLs in `loadCKEditorCloud`.
2. Added support for passing a translations list for `CKBox` in the configuration for `loadCKEditorCloud`.
3. Improved detection of already installed versions of the editor. 
Please read more about these changes in our post [here](https://github.com/ckeditor/ckeditor5/issues/17317).
=> Release `v2.2.0`

src/cdn/ck/createCKCdnBaseBundlePack.ts, src/cdn/ck/createCKCdnPremiumBundlePack.ts, src/cdn/loadCKEditorCloud.ts, src/cdn/utils/combineCKCdnBundlesPacks.ts, src/installation-info/getSupportedLicenseVersionInstallationInfo.ts, src/license/getLicenseVersionFromEditorVersion.ts, src/license/isCKCdnSupportedByEditorVersion.ts, tests/cdn/loadCKEditorCloud.test.ts, tests/license/isCKCdnSupportedByEditorVersion.test.ts
Feature: Check minimum supported editor version before injecting cloud files. 
---
No longer raise this kind of errors when too old editor version is passed:
```@ckeditor_ckeditor5-react.js?v=4b120bc5:2535 Error: Window entry "CKEDITOR" not found.
at @ckeditor_ckeditor5-react.js?v=4b120bc5:1011:15
at tick (@ckeditor_ckeditor5-react.js?v=4b120bc5:811:30)```
=> Add supported editor version check to CDN loader.

src/cdn/ck/createCKCdnBaseBundlePack.ts, tests/cdn/ck/createCKCdnBaseBundlePack.test.ts
Fix: Updated migration link for Vanilla JS when the editor is installed via NPM but loaded via CDN.
---
Parent issue https://github.com/ckeditor/ckeditor5/issues/18510
=> Adjust vanilla-js migrations path.
